function [ P ] = UntaggedBitsProb( mu_0,sig,frac )
%untagged bits 信号 理论概率
Nmin=(1-frac)*mu_0;
Nmax=(1+frac)*mu_0;

P = 1 - integral(@(mu) ...
    0.5 .* ( ...
        erf((Nmax - mu) ./ sqrt(2 .* mu)) - ...
        erf((Nmin - mu) ./ sqrt(2 .* mu)) ) .* ...
    (1 ./ (sqrt(2*pi) .* sig)) .* ...
    exp(-((mu - mu_0).^2) ./ (2 .* sig.^2)), ...
    Nmin, Nmax, 'ArrayValued', true, 'RelTol', 1e-10, 'AbsTol', 1e-12);

end

